require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BottlesController do

  # This should return the minimal set of attributes required to create a valid
  # Bottle. As you add validations to Bottle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bottles as @bottles" do
      bottle = Bottle.create! valid_attributes
      get :index
      assigns(:bottles).should eq([bottle])
    end
  end

  describe "GET show" do
    it "assigns the requested bottle as @bottle" do
      bottle = Bottle.create! valid_attributes
      get :show, :id => bottle.id.to_s
      assigns(:bottle).should eq(bottle)
    end
  end

  describe "GET new" do
    it "assigns a new bottle as @bottle" do
      get :new
      assigns(:bottle).should be_a_new(Bottle)
    end
  end

  describe "GET edit" do
    it "assigns the requested bottle as @bottle" do
      bottle = Bottle.create! valid_attributes
      get :edit, :id => bottle.id.to_s
      assigns(:bottle).should eq(bottle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bottle" do
        expect {
          post :create, :bottle => valid_attributes
        }.to change(Bottle, :count).by(1)
      end

      it "assigns a newly created bottle as @bottle" do
        post :create, :bottle => valid_attributes
        assigns(:bottle).should be_a(Bottle)
        assigns(:bottle).should be_persisted
      end

      it "redirects to the created bottle" do
        post :create, :bottle => valid_attributes
        response.should redirect_to(Bottle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bottle as @bottle" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bottle.any_instance.stub(:save).and_return(false)
        post :create, :bottle => {}
        assigns(:bottle).should be_a_new(Bottle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bottle.any_instance.stub(:save).and_return(false)
        post :create, :bottle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bottle" do
        bottle = Bottle.create! valid_attributes
        # Assuming there are no other bottles in the database, this
        # specifies that the Bottle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bottle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bottle.id, :bottle => {'these' => 'params'}
      end

      it "assigns the requested bottle as @bottle" do
        bottle = Bottle.create! valid_attributes
        put :update, :id => bottle.id, :bottle => valid_attributes
        assigns(:bottle).should eq(bottle)
      end

      it "redirects to the bottle" do
        bottle = Bottle.create! valid_attributes
        put :update, :id => bottle.id, :bottle => valid_attributes
        response.should redirect_to(bottle)
      end
    end

    describe "with invalid params" do
      it "assigns the bottle as @bottle" do
        bottle = Bottle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bottle.any_instance.stub(:save).and_return(false)
        put :update, :id => bottle.id.to_s, :bottle => {}
        assigns(:bottle).should eq(bottle)
      end

      it "re-renders the 'edit' template" do
        bottle = Bottle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bottle.any_instance.stub(:save).and_return(false)
        put :update, :id => bottle.id.to_s, :bottle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bottle" do
      bottle = Bottle.create! valid_attributes
      expect {
        delete :destroy, :id => bottle.id.to_s
      }.to change(Bottle, :count).by(-1)
    end

    it "redirects to the bottles list" do
      bottle = Bottle.create! valid_attributes
      delete :destroy, :id => bottle.id.to_s
      response.should redirect_to(bottles_url)
    end
  end

end
